### ISSUE TITLE
header nav buttons should be responsive in ipad devise

### ISSUE THREAD

**Issue by SykWeb** [SykWeb-ORG/Sykweb_Site#26]

**Comment by soufianeElkaabaoui** [comment]
PJ
![header-buttons](https://user-images.githubusercontent.com/100730344/193609498-9e151ddc-8c82-4e0e-9caa-7eed9fdb124e.PNG)

**Comment by AyoubKhyat** [comment]
Oke i will see

**Comment by AyoubKhyat** [comment]
Done
